### PR TITLE
Add beat ratio display after AC

### PR DESCRIPTION
**Pull request by fanzhenya**
Sample output:
    ✔ Accepted
    ✔ 1562/1562 cases passed (53 ms)
    ✔ Your runtime beats 74.21 % of java submissions

Signed-off-by: Fan Zhenya <fzywork@163.com>

### CODE REVIEW

**Comment by fanzhenya** [comment]
@skygragon

**Comment by skygragon** [comment]
Sorry I'm busying in work those days, will get back to u this weekend I hope :)

**Comment by skygragon** [comment]
Thanks for contributing this!

**Comment by fanzhenya** [comment]
@skygragon  happy coding :)

**Pull request merged**
